"""
HTML reporter — outputs a rich, self-contained interactive HTML report.

Features:
  - Dark mode design with a professional colour palette
  - Severity summary cards with counts
  - Collapsible issue cards grouped by severity
  - Syntax-highlighted log context
  - Embedded SVG severity chart
  - Fully self-contained (no external CDN dependencies)
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from typing import List

from log_analyzer.models import AnalysisReport, Issue, Severity
from log_analyzer.reporters.base import BaseReporter

_SEVERITY_COLOR = {
    Severity.CRITICAL: ("#ff4d4d", "#3d0000"),
    Severity.ERROR: ("#ff8c42", "#3d1800"),
    Severity.WARNING: ("#ffd166", "#3d2e00"),
    Severity.INFO: ("#4fc3f7", "#00263d"),
}

_SEVERITY_ICON = {
    Severity.CRITICAL: "🔴",
    Severity.ERROR: "🟠",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}


def _esc(text: str) -> str:
    return html.escape(str(text))


class HtmlReporter(BaseReporter):
    """Renders a self-contained, dark-mode HTML report."""

    extension = "html"

    def render(self, report: AnalysisReport) -> str:
        summary = report.summary
        sorted_issues = report.sorted_issues

        issue_cards = "\n".join(_render_issue_card(i, idx) for idx, i in enumerate(sorted_issues, 1))

        chart_data = json.dumps({
            "critical": summary["critical"],
            "error": summary["error"],
            "warning": summary["warning"],
            "info": summary["info"],
        })

        no_issues_html = ""
        if not sorted_issues:
            no_issues_html = """
            <div class="no-issues">
                <span class="no-issues-icon">✅</span>
                <h2>No Issues Detected</h2>
                <p>The log appears healthy — no errors, warnings, or performance issues were found.</p>
            </div>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Log Analysis Report — {_esc(report.file_path)}</title>
  <meta name="description" content="Log analysis report for {_esc(report.file_path)} generated by Log Analyzer." />
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

    :root {{
      --bg: #0d1117;
      --bg2: #161b22;
      --bg3: #21262d;
      --border: #30363d;
      --text: #e6edf3;
      --text-muted: #8b949e;
      --accent: #58a6ff;
      --critical: #ff4d4d;
      --critical-bg: rgba(255,77,77,0.12);
      --error: #ff8c42;
      --error-bg: rgba(255,140,66,0.12);
      --warning: #ffd166;
      --warning-bg: rgba(255,209,102,0.12);
      --info: #4fc3f7;
      --info-bg: rgba(79,195,247,0.12);
      --green: #3fb950;
      --radius: 10px;
      --shadow: 0 4px 24px rgba(0,0,0,0.4);
    }}

    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif;
      background: var(--bg);
      color: var(--text);
      line-height: 1.6;
      min-height: 100vh;
    }}

    /* ---- Header ---- */
    .header {{
      background: linear-gradient(135deg, #1a1f2e 0%, #0d1117 60%, #1a2333 100%);
      border-bottom: 1px solid var(--border);
      padding: 2.5rem 2rem 2rem;
      position: relative;
      overflow: hidden;
    }}
    .header::before {{
      content: '';
      position: absolute;
      top: -80px; right: -80px;
      width: 300px; height: 300px;
      background: radial-gradient(circle, rgba(88,166,255,0.08) 0%, transparent 70%);
      border-radius: 50%;
    }}
    .header-inner {{ max-width: 1200px; margin: 0 auto; position: relative; }}
    .header-badge {{
      display: inline-flex; align-items: center; gap: 8px;
      background: rgba(88,166,255,0.15); border: 1px solid rgba(88,166,255,0.3);
      border-radius: 20px; padding: 4px 14px; font-size: 0.8rem;
      color: var(--accent); margin-bottom: 1rem;
    }}
    .header h1 {{ font-size: 2rem; font-weight: 700; letter-spacing: -0.03em; }}
    .header h1 span {{ color: var(--accent); }}
    .header-meta {{
      display: flex; flex-wrap: wrap; gap: 1.5rem; margin-top: 1rem;
      color: var(--text-muted); font-size: 0.875rem;
    }}
    .header-meta span {{ display: flex; align-items: center; gap: 6px; }}

    /* ---- Main ---- */
    .main {{ max-width: 1200px; margin: 0 auto; padding: 2rem; }}

    /* ---- Summary Cards ---- */
    .summary-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 1rem; margin-bottom: 2.5rem;
    }}
    .summary-card {{
      background: var(--bg2);
      border: 1px solid var(--border);
      border-radius: var(--radius);
      padding: 1.25rem 1.5rem;
      position: relative; overflow: hidden;
      transition: transform 0.2s, box-shadow 0.2s;
    }}
    .summary-card:hover {{ transform: translateY(-2px); box-shadow: var(--shadow); }}
    .summary-card::before {{
      content: ''; position: absolute; top: 0; left: 0; right: 0;
      height: 3px; border-radius: var(--radius) var(--radius) 0 0;
    }}
    .summary-card.critical::before {{ background: var(--critical); }}
    .summary-card.error::before {{ background: var(--error); }}
    .summary-card.warning::before {{ background: var(--warning); }}
    .summary-card.info::before {{ background: var(--info); }}
    .summary-card.total::before {{ background: var(--accent); }}
    .card-label {{
      font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.1em;
      color: var(--text-muted); margin-bottom: 0.5rem;
    }}
    .card-count {{
      font-size: 2.5rem; font-weight: 700; line-height: 1;
    }}
    .summary-card.critical .card-count {{ color: var(--critical); }}
    .summary-card.error .card-count {{ color: var(--error); }}
    .summary-card.warning .card-count {{ color: var(--warning); }}
    .summary-card.info .card-count {{ color: var(--info); }}
    .summary-card.total .card-count {{ color: var(--accent); }}

    /* ---- Chart ---- */
    .chart-section {{
      background: var(--bg2); border: 1px solid var(--border);
      border-radius: var(--radius); padding: 1.5rem; margin-bottom: 2.5rem;
    }}
    .chart-title {{
      font-size: 1rem; font-weight: 600; color: var(--text-muted);
      margin-bottom: 1rem; text-transform: uppercase; letter-spacing: 0.05em;
    }}
    .chart-bars {{ display: flex; flex-direction: column; gap: 0.75rem; }}
    .chart-row {{ display: flex; align-items: center; gap: 1rem; }}
    .chart-label {{ width: 80px; font-size: 0.875rem; color: var(--text-muted); flex-shrink: 0; }}
    .chart-bar-track {{
      flex: 1; height: 20px; background: var(--bg3);
      border-radius: 4px; overflow: hidden;
    }}
    .chart-bar {{
      height: 100%; border-radius: 4px;
      transition: width 0.6s cubic-bezier(0.4,0,0.2,1);
    }}
    .chart-bar.critical {{ background: var(--critical); }}
    .chart-bar.error {{ background: var(--error); }}
    .chart-bar.warning {{ background: var(--warning); }}
    .chart-bar.info {{ background: var(--info); }}
    .chart-value {{ width: 30px; text-align: right; font-size: 0.875rem; font-weight: 600; }}

    /* ---- Issues ---- */
    .issues-header {{
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 1.25rem;
    }}
    .issues-title {{ font-size: 1.25rem; font-weight: 700; }}
    .filter-bar {{
      display: flex; gap: 0.5rem; flex-wrap: wrap; margin-bottom: 1.5rem;
    }}
    .filter-btn {{
      padding: 5px 14px; border-radius: 20px; border: 1px solid var(--border);
      background: var(--bg2); color: var(--text-muted); font-size: 0.8rem;
      cursor: pointer; transition: all 0.2s;
    }}
    .filter-btn:hover, .filter-btn.active {{
      background: var(--accent); color: var(--bg); border-color: var(--accent);
      font-weight: 600;
    }}

    .issue-card {{
      background: var(--bg2); border: 1px solid var(--border);
      border-radius: var(--radius); margin-bottom: 1rem; overflow: hidden;
      transition: box-shadow 0.2s;
    }}
    .issue-card:hover {{ box-shadow: var(--shadow); }}
    .issue-card.severity-CRITICAL {{ border-left: 4px solid var(--critical); }}
    .issue-card.severity-ERROR {{ border-left: 4px solid var(--error); }}
    .issue-card.severity-WARNING {{ border-left: 4px solid var(--warning); }}
    .issue-card.severity-INFO {{ border-left: 4px solid var(--info); }}

    .issue-header {{
      display: flex; align-items: center; gap: 1rem; padding: 1rem 1.25rem;
      cursor: pointer; user-select: none;
    }}
    .issue-header:hover {{ background: rgba(255,255,255,0.03); }}
    .severity-badge {{
      padding: 3px 10px; border-radius: 12px; font-size: 0.75rem;
      font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;
      flex-shrink: 0;
    }}
    .severity-badge.CRITICAL {{ background: var(--critical-bg); color: var(--critical); border: 1px solid rgba(255,77,77,0.3); }}
    .severity-badge.ERROR {{ background: var(--error-bg); color: var(--error); border: 1px solid rgba(255,140,66,0.3); }}
    .severity-badge.WARNING {{ background: var(--warning-bg); color: var(--warning); border: 1px solid rgba(255,209,102,0.3); }}
    .severity-badge.INFO {{ background: var(--info-bg); color: var(--info); border: 1px solid rgba(79,195,247,0.3); }}

    .issue-title {{ font-weight: 600; flex: 1; }}
    .issue-meta-inline {{
      font-size: 0.75rem; color: var(--text-muted); margin-left: auto; white-space: nowrap;
    }}
    .chevron {{
      color: var(--text-muted); transition: transform 0.25s; flex-shrink: 0;
    }}
    .issue-card.open .chevron {{ transform: rotate(180deg); }}

    .issue-body {{
      display: none; padding: 0 1.25rem 1.25rem; border-top: 1px solid var(--border);
    }}
    .issue-card.open .issue-body {{ display: block; }}

    .meta-grid {{
      display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 0.5rem; margin: 1rem 0;
    }}
    .meta-item {{ font-size: 0.8rem; color: var(--text-muted); }}
    .meta-item strong {{ color: var(--text); }}

    .section-label {{
      font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.08em;
      color: var(--text-muted); margin: 1rem 0 0.5rem; font-weight: 600;
    }}
    .log-context {{
      background: var(--bg); border: 1px solid var(--border);
      border-radius: 6px; overflow: auto; font-family: 'JetBrains Mono', 'Fira Code', monospace;
      font-size: 0.78rem; line-height: 1.7;
    }}
    .log-context pre {{ padding: 0.75rem 1rem; }}
    .log-line {{ display: flex; }}
    .log-line-no {{
      color: var(--text-muted); margin-right: 1rem; user-select: none;
      min-width: 50px; text-align: right; flex-shrink: 0;
    }}
    .log-line-text {{ color: #c9d1d9; word-break: break-all; }}
    .log-line-text.err {{ color: var(--critical); }}
    .log-line-text.warn {{ color: var(--warning); }}

    .remediation-list {{
      list-style: none; display: flex; flex-direction: column; gap: 0.5rem;
    }}
    .remediation-list li {{
      display: flex; gap: 0.75rem; align-items: flex-start;
      background: var(--bg3); border-radius: 6px; padding: 0.6rem 0.9rem;
      font-size: 0.875rem;
    }}
    .step-num {{
      background: var(--accent); color: var(--bg);
      width: 22px; height: 22px; border-radius: 50%;
      display: flex; align-items: center; justify-content: center;
      font-size: 0.7rem; font-weight: 700; flex-shrink: 0; margin-top: 1px;
    }}
    .references-list {{ list-style: none; display: flex; flex-direction: column; gap: 0.25rem; }}
    .references-list a {{ color: var(--accent); font-size: 0.85rem; text-decoration: none; }}
    .references-list a:hover {{ text-decoration: underline; }}

    .no-issues {{
      text-align: center; padding: 4rem 2rem;
      background: var(--bg2); border: 1px solid var(--border);
      border-radius: var(--radius);
    }}
    .no-issues-icon {{ font-size: 4rem; display: block; margin-bottom: 1rem; }}
    .no-issues h2 {{ font-size: 1.5rem; color: var(--green); margin-bottom: 0.5rem; }}
    .no-issues p {{ color: var(--text-muted); }}

    /* ---- Footer ---- */
    .footer {{
      text-align: center; padding: 2rem;
      color: var(--text-muted); font-size: 0.8rem;
      border-top: 1px solid var(--border); margin-top: 3rem;
    }}

    @media (max-width: 640px) {{
      .header {{ padding: 1.5rem 1rem; }}
      .main {{ padding: 1rem; }}
      .header h1 {{ font-size: 1.4rem; }}
      .summary-grid {{ grid-template-columns: repeat(2, 1fr); }}
    }}
  </style>
</head>
<body>

<!-- Header -->
<header class="header">
  <div class="header-inner">
    <div class="header-badge">🔍 Log Analyzer Report</div>
    <h1>Log Analysis <span>Report</span></h1>
    <div class="header-meta">
      <span>📄 <strong>{_esc(report.file_path)}</strong></span>
      <span>🏷️ {_esc(report.source.value.title())}</span>
      <span>📅 {_esc(report.analyzed_at.strftime('%Y-%m-%d %H:%M UTC'))}</span>
      <span>📏 {report.total_lines:,} lines processed</span>
    </div>
  </div>
</header>

<main class="main">

  <!-- Summary Cards -->
  <div class="summary-grid">
    <div class="summary-card total">
      <div class="card-label">Total Issues</div>
      <div class="card-count">{summary['total']}</div>
    </div>
    <div class="summary-card critical">
      <div class="card-label">Critical</div>
      <div class="card-count">{summary['critical']}</div>
    </div>
    <div class="summary-card error">
      <div class="card-label">Error</div>
      <div class="card-count">{summary['error']}</div>
    </div>
    <div class="summary-card warning">
      <div class="card-label">Warning</div>
      <div class="card-count">{summary['warning']}</div>
    </div>
    <div class="summary-card info">
      <div class="card-label">Info</div>
      <div class="card-count">{summary['info']}</div>
    </div>
  </div>

  <!-- Bar Chart -->
  {_render_chart(summary)}

  <!-- Issues -->
  <div class="issues-header">
    <div class="issues-title">🔍 Detected Issues</div>
  </div>

  <div class="filter-bar">
    <button class="filter-btn active" onclick="filterIssues('all', this)">All ({summary['total']})</button>
    <button class="filter-btn" onclick="filterIssues('CRITICAL', this)">🔴 Critical ({summary['critical']})</button>
    <button class="filter-btn" onclick="filterIssues('ERROR', this)">🟠 Error ({summary['error']})</button>
    <button class="filter-btn" onclick="filterIssues('WARNING', this)">🟡 Warning ({summary['warning']})</button>
    <button class="filter-btn" onclick="filterIssues('INFO', this)">🔵 Info ({summary['info']})</button>
  </div>

  <div id="issues-container">
    {no_issues_html}
    {issue_cards}
  </div>

</main>

<footer class="footer">
  Generated by <strong>Log Analyzer</strong> &mdash; {_esc(datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'))}
</footer>

<script>
  // Toggle issue cards
  document.querySelectorAll('.issue-header').forEach(header => {{
    header.addEventListener('click', () => {{
      header.closest('.issue-card').classList.toggle('open');
    }});
  }});

  // Auto-open the first critical/error card
  const firstImportant = document.querySelector('.issue-card.severity-CRITICAL, .issue-card.severity-ERROR');
  if (firstImportant) firstImportant.classList.add('open');

  // Filter buttons
  function filterIssues(severity, btn) {{
    document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
    btn.classList.add('active');
    document.querySelectorAll('.issue-card').forEach(card => {{
      if (severity === 'all' || card.dataset.severity === severity) {{
        card.style.display = '';
      }} else {{
        card.style.display = 'none';
      }}
    }});
  }}

  // Animate bars on load
  window.addEventListener('load', () => {{
    const chartData = {chart_data};
    const total = Math.max(chartData.critical + chartData.error + chartData.warning + chartData.info, 1);
    document.querySelectorAll('.chart-bar[data-count]').forEach(bar => {{
      const count = parseInt(bar.dataset.count);
      bar.style.width = (count / total * 100) + '%';
    }});
  }});
</script>
</body>
</html>"""

    # ------------------------------------------------------------------


def _render_chart(summary: dict) -> str:
    total = max(summary["critical"] + summary["error"] + summary["warning"] + summary["info"], 1)

    def bar(cls, label, count):
        pct = count / total * 100
        return f"""
    <div class="chart-row">
      <div class="chart-label">{label}</div>
      <div class="chart-bar-track">
        <div class="chart-bar {cls}" data-count="{count}" style="width:{pct:.1f}%"></div>
      </div>
      <div class="chart-value">{count}</div>
    </div>"""

    return f"""
  <div class="chart-section">
    <div class="chart-title">Issues by Severity</div>
    <div class="chart-bars">
      {bar('critical', 'Critical', summary['critical'])}
      {bar('error', 'Error', summary['error'])}
      {bar('warning', 'Warning', summary['warning'])}
      {bar('info', 'Info', summary['info'])}
    </div>
  </div>"""


def _render_issue_card(issue: Issue, idx: int) -> str:
    sev = issue.severity.value
    icon = _SEVERITY_ICON.get(issue.severity, "⚪")
    line_str = ", ".join(str(n) for n in issue.line_numbers[:5])
    if len(issue.line_numbers) > 5:
        line_str += f" (+{len(issue.line_numbers)-5} more)"

    # Context lines
    ctx_lines = ""
    for evt in issue.events[:8]:
        raw_esc = _esc(evt.raw.rstrip())
        cls = "err" if evt.level in ("ERROR", "CRITICAL", "FATAL") else (
            "warn" if evt.level in ("WARNING", "WARN") else ""
        )
        ctx_lines += f'<div class="log-line"><span class="log-line-no">L{evt.line_number}</span><span class="log-line-text {cls}">{raw_esc}</span></div>\n'
    if len(issue.events) > 8:
        ctx_lines += f'<div class="log-line"><span class="log-line-no">...</span><span class="log-line-text" style="color:var(--text-muted)">({len(issue.events)-8} more lines)</span></div>\n'

    # Remediation
    rem_html = ""
    if issue.remediation:
        items = "".join(
            f'<li><span class="step-num">{i}</span><span>{_esc(step)}</span></li>'
            for i, step in enumerate(issue.remediation, 1)
        )
        rem_html = f'<div class="section-label">🔧 Remediation Steps</div><ul class="remediation-list">{items}</ul>'

    # References
    refs_html = ""
    if issue.references:
        ref_items = "".join(
            f'<li><a href="{_esc(r)}" target="_blank" rel="noopener">{_esc(r)}</a></li>'
            for r in issue.references
        )
        refs_html = f'<div class="section-label">📚 References</div><ul class="references-list">{ref_items}</ul>'

    return f"""
<div class="issue-card severity-{sev}" data-severity="{sev}" id="issue-{_esc(issue.id)}">
  <div class="issue-header">
    <span class="severity-badge {sev}">{sev}</span>
    <span class="issue-title">{idx}. {_esc(issue.title)}</span>
    <span class="issue-meta-inline">Line {_esc(line_str)}</span>
    <svg class="chevron" width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
      <path d="M1.646 4.646a.5.5 0 01.708 0L8 10.293l5.646-5.647a.5.5 0 01.708.708l-6 6a.5.5 0 01-.708 0l-6-6a.5.5 0 010-.708z"/>
    </svg>
  </div>
  <div class="issue-body">
    <div class="meta-grid">
      <div class="meta-item"><strong>ID:</strong> <code>{_esc(issue.id)}</code></div>
      <div class="meta-item"><strong>Category:</strong> {_esc(issue.category.value)}</div>
      <div class="meta-item"><strong>Source:</strong> {_esc(issue.source.value.title())}</div>
      <div class="meta-item"><strong>Detector:</strong> {_esc(issue.detector)}</div>
    </div>
    <div class="section-label">📋 Log Context</div>
    <div class="log-context"><pre>{ctx_lines}</pre></div>
    {rem_html}
    {refs_html}
  </div>
</div>"""
