"""
Markdown reporter — outputs a human-readable Markdown report.

Produces:
  - Executive summary table (counts by severity)
  - Per-issue sections with context lines and remediation steps
  - References section
"""

from __future__ import annotations

from datetime import datetime
from typing import List

from log_analyzer.models import AnalysisReport, Issue, Severity
from log_analyzer.reporters.base import BaseReporter

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.ERROR: "🟠",
    Severity.WARNING: "🟡",
    Severity.INFO: "🔵",
}

_SEP = "---"


class MarkdownReporter(BaseReporter):
    """Renders a Markdown report with summary, issue details, and remediation."""

    extension = "md"

    def render(self, report: AnalysisReport) -> str:
        lines: List[str] = []

        # ------------------------------------------------------------------ Header
        lines += [
            f"# 📊 Log Analysis Report",
            "",
            f"| Field | Value |",
            f"|---|---|",
            f"| **File** | `{report.file_path}` |",
            f"| **Source** | {report.source.value.title()} |",
            f"| **Analyzed At** | {report.analyzed_at.strftime('%Y-%m-%d %H:%M:%S UTC')} |",
            f"| **Total Lines** | {report.total_lines:,} |",
            f"| **Issues Found** | {report.summary['total']} |",
            "",
        ]

        # ------------------------------------------------------------------ Summary
        lines += [
            "## 📈 Summary",
            "",
            "| Severity | Count |",
            "|---|---|",
            f"| 🔴 Critical | {report.summary['critical']} |",
            f"| 🟠 Error | {report.summary['error']} |",
            f"| 🟡 Warning | {report.summary['warning']} |",
            f"| 🔵 Info | {report.summary['info']} |",
            f"| **Total** | **{report.summary['total']}** |",
            "",
        ]

        if not report.issues:
            lines += [
                "> ✅ **No issues detected.** The log appears healthy.",
                "",
            ]
            return "\n".join(lines)

        # ------------------------------------------------------------------ Issues
        lines += ["## 🔍 Detected Issues", ""]

        for idx, issue in enumerate(report.sorted_issues, start=1):
            emoji = _SEVERITY_EMOJI.get(issue.severity, "⚪")
            lines += [
                f"### {idx}. {emoji} {issue.title}",
                "",
                f"| Field | Value |",
                f"|---|---|",
                f"| **ID** | `{issue.id}` |",
                f"| **Severity** | {issue.severity.value} |",
                f"| **Category** | {issue.category.value} |",
                f"| **Source** | {issue.source.value.title()} |",
                f"| **Detector** | `{issue.detector}` |",
                f"| **Line(s)** | {', '.join(str(n) for n in issue.line_numbers)} |",
                "",
            ]

            # Context
            if issue.events:
                lines += ["**Log Context:**", "", "```"]
                for evt in issue.events[:5]:  # cap at 5 context lines
                    lines.append(f"L{evt.line_number:>5}: {evt.raw.rstrip()}")
                if len(issue.events) > 5:
                    lines.append(f"       ... ({len(issue.events) - 5} more lines)")
                lines += ["```", ""]

            # Remediation
            if issue.remediation:
                lines += ["**🔧 Remediation Steps:**", ""]
                for step_no, step in enumerate(issue.remediation, start=1):
                    lines.append(f"{step_no}. {step}")
                lines.append("")

            # References
            if issue.references:
                lines += ["**📚 References:**", ""]
                for ref in issue.references:
                    lines.append(f"- [{ref}]({ref})")
                lines.append("")

            lines.append(_SEP)
            lines.append("")

        # ------------------------------------------------------------------ Footer
        lines += [
            "---",
            "",
            f"*Generated by [Log Analyzer](https://github.com/log-analyzer) — "
            f"{datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
        ]

        return "\n".join(lines)
